/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.AdminController;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.JTextPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tri Jaka
 */
public class AdminFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminFrame
     */
    public AdminFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butGroupJenis = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        lokasiBtn = new javax.swing.JButton();
        transportBtn = new javax.swing.JButton();
        userBtn = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lokTabPane = new javax.swing.JTabbedPane();
        tambahLokPanel = new javax.swing.JPanel();
        namaTempatField = new javax.swing.JTextField();
        wisRBtn = new javax.swing.JRadioButton();
        nonWisRBtn = new javax.swing.JRadioButton();
        idField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        descPane = new javax.swing.JTextPane();
        pilihLokBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tarifLok = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        hapusLokPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnHapusNonWisata = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbWisata = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        tbNonWisata = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        btnHapusWisata = new javax.swing.JButton();
        transTabPane = new javax.swing.JTabbedPane();
        tambahTransPanel = new javax.swing.JPanel();
        fieldNamaTrans = new javax.swing.JTextField();
        rBtnTransA = new javax.swing.JRadioButton();
        rBtnTransB = new javax.swing.JRadioButton();
        fieldNoPol = new javax.swing.JTextField();
        btnSubmitTrans = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        fieldKapasitas = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        fieldTarifTrans = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        labelKode = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbRute = new javax.swing.JTable();
        jLabel25 = new javax.swing.JLabel();
        cBoxLokasi = new javax.swing.JComboBox<>();
        btnTambahRute = new javax.swing.JButton();
        btnHapusRute = new javax.swing.JButton();
        hapusTransPanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btnHapusBus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbBus = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        tbAngkot = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        btnHapusAngkot = new javax.swing.JButton();
        uATabPane = new javax.swing.JTabbedPane();
        adminPanel = new javax.swing.JPanel();
        fieldUnameAdmin = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        fieldPassAdmin = new javax.swing.JPasswordField();
        btnTambahAdmin = new javax.swing.JButton();
        btnHapusAdmin = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        tbAdmin = new javax.swing.JTable();
        fieldNamaAdmin = new javax.swing.JTextField();
        fieldEmailAdmin = new javax.swing.JTextField();
        fieldNoHPAdmin = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        userPanel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        btnHapusUser = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        tbUser = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 500));
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setPreferredSize(new java.awt.Dimension(335, 200));

        lokasiBtn.setBackground(new java.awt.Color(204, 204, 204));
        lokasiBtn.setText("Edit Lokasi");
        lokasiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lokasiBtnActionPerformed(evt);
            }
        });

        transportBtn.setBackground(new java.awt.Color(204, 204, 204));
        transportBtn.setText("Edit Transport");
        transportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transportBtnActionPerformed(evt);
            }
        });

        userBtn.setBackground(new java.awt.Color(204, 204, 204));
        userBtn.setText("Edit Admin & User");
        userBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userBtnActionPerformed(evt);
            }
        });

        btnLogOut.setBackground(new java.awt.Color(204, 204, 204));
        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lokasiBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(transportBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(userBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLogOut)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLogOut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lokasiBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setLayout(new java.awt.CardLayout());

        butGroupJenis.add(wisRBtn);
        wisRBtn.setText("Wisata");
        wisRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wisRBtnActionPerformed(evt);
            }
        });

        butGroupJenis.add(nonWisRBtn);
        nonWisRBtn.setText("Non-Wisata");
        nonWisRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nonWisRBtnActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(descPane);

        pilihLokBox.setBackground(new java.awt.Color(102, 102, 102));
        pilihLokBox.setForeground(new java.awt.Color(255, 255, 255));
        pilihLokBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bandung Kota", "Bandung Barat", "Bandung Utara", "Bandung Selatan" }));

        jLabel1.setText("Nama Tempat: ");

        jLabel2.setText("Jenis: ");

        jLabel3.setText("ID Baru:");

        jLabel4.setText("Lokasi: ");

        jLabel6.setText("Deskripsi Tempat:");

        tarifLok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarifLokActionPerformed(evt);
            }
        });

        btnSubmit.setBackground(java.awt.SystemColor.controlDkShadow);
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Submit");

        jLabel24.setText("Tarif:");

        javax.swing.GroupLayout tambahLokPanelLayout = new javax.swing.GroupLayout(tambahLokPanel);
        tambahLokPanel.setLayout(tambahLokPanelLayout);
        tambahLokPanelLayout.setHorizontalGroup(
            tambahLokPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahLokPanelLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(tambahLokPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addComponent(idField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tambahLokPanelLayout.createSequentialGroup()
                        .addComponent(wisRBtn)
                        .addGap(18, 18, 18)
                        .addComponent(nonWisRBtn))
                    .addComponent(namaTempatField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addComponent(pilihLokBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(tambahLokPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(tambahLokPanelLayout.createSequentialGroup()
                        .addGroup(tambahLokPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(tarifLok, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addGap(0, 160, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tambahLokPanelLayout.setVerticalGroup(
            tambahLokPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahLokPanelLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(tambahLokPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tambahLokPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(tambahLokPanelLayout.createSequentialGroup()
                        .addComponent(namaTempatField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tambahLokPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(wisRBtn)
                            .addComponent(nonWisRBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tambahLokPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tambahLokPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pilihLokBox, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tarifLok, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pilihLokBox.getAccessibleContext().setAccessibleDescription("");

        lokTabPane.addTab("Tambah", tambahLokPanel);

        jLabel5.setText("Pilih Non-Wisata:");

        btnHapusNonWisata.setBackground(new java.awt.Color(102, 102, 102));
        btnHapusNonWisata.setForeground(new java.awt.Color(255, 255, 255));
        btnHapusNonWisata.setText("Hapus");

        tbWisata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(tbWisata);

        tbNonWisata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(tbNonWisata);

        jLabel17.setText("Pilih Wisata:");

        btnHapusWisata.setBackground(new java.awt.Color(102, 102, 102));
        btnHapusWisata.setForeground(new java.awt.Color(255, 255, 255));
        btnHapusWisata.setText("Hapus");

        javax.swing.GroupLayout hapusLokPanelLayout = new javax.swing.GroupLayout(hapusLokPanel);
        hapusLokPanel.setLayout(hapusLokPanelLayout);
        hapusLokPanelLayout.setHorizontalGroup(
            hapusLokPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hapusLokPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hapusLokPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hapusLokPanelLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(hapusLokPanelLayout.createSequentialGroup()
                        .addGroup(hapusLokPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(hapusLokPanelLayout.createSequentialGroup()
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnHapusWisata, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
                            .addGroup(hapusLokPanelLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(hapusLokPanelLayout.createSequentialGroup()
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnHapusNonWisata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        hapusLokPanelLayout.setVerticalGroup(
            hapusLokPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hapusLokPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(hapusLokPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnHapusWisata, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(hapusLokPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnHapusNonWisata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                .addGap(76, 76, 76))
        );

        lokTabPane.addTab("Hapus", hapusLokPanel);

        jPanel3.add(lokTabPane, "card2");

        fieldNamaTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNamaTransActionPerformed(evt);
            }
        });

        butGroupJenis.add(rBtnTransA);
        rBtnTransA.setSelected(true);
        rBtnTransA.setText("Angkot");
        rBtnTransA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnTransAActionPerformed(evt);
            }
        });

        butGroupJenis.add(rBtnTransB);
        rBtnTransB.setText("Bus");
        rBtnTransB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnTransBActionPerformed(evt);
            }
        });

        btnSubmitTrans.setBackground(java.awt.SystemColor.controlDkShadow);
        btnSubmitTrans.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmitTrans.setText("Submit");

        jLabel7.setText("Nama Transportasi:");

        jLabel8.setText("Jenis: ");

        jLabel9.setText("No. Polisi:");

        fieldKapasitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldKapasitasActionPerformed(evt);
            }
        });

        jLabel19.setText("Kapasitas:");

        jLabel18.setText("Tarif:");

        jLabel16.setText("Kode:");

        labelKode.setText("kode");

        tbRute.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tbRute);

        jLabel25.setText("Rute:");

        cBoxLokasi.setBackground(new java.awt.Color(102, 102, 102));
        cBoxLokasi.setForeground(new java.awt.Color(255, 255, 255));
        cBoxLokasi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bandung Kota", "Bandung Utara", "Bandung Barat", "Bandung Selatan" }));

        btnTambahRute.setBackground(new java.awt.Color(102, 102, 102));
        btnTambahRute.setForeground(new java.awt.Color(255, 255, 255));
        btnTambahRute.setText("tambah");

        btnHapusRute.setBackground(new java.awt.Color(102, 102, 102));
        btnHapusRute.setForeground(new java.awt.Color(255, 255, 255));
        btnHapusRute.setText("hapus");

        javax.swing.GroupLayout tambahTransPanelLayout = new javax.swing.GroupLayout(tambahTransPanel);
        tambahTransPanel.setLayout(tambahTransPanelLayout);
        tambahTransPanelLayout.setHorizontalGroup(
            tambahTransPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahTransPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tambahTransPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addGroup(tambahTransPanelLayout.createSequentialGroup()
                        .addGroup(tambahTransPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tambahTransPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnSubmitTrans, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fieldNoPol)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tambahTransPanelLayout.createSequentialGroup()
                                    .addComponent(rBtnTransA)
                                    .addGap(18, 18, 18)
                                    .addComponent(rBtnTransB))
                                .addComponent(fieldNamaTrans, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))
                            .addComponent(jLabel7)
                            .addComponent(jLabel19)
                            .addComponent(fieldKapasitas, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(tambahTransPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(fieldTarifTrans, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(tambahTransPanelLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelKode))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25)
                            .addGroup(tambahTransPanelLayout.createSequentialGroup()
                                .addComponent(cBoxLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnTambahRute))
                            .addComponent(btnHapusRute))))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        tambahTransPanelLayout.setVerticalGroup(
            tambahTransPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahTransPanelLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(tambahTransPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tambahTransPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fieldTarifTrans)
                    .addComponent(fieldNamaTrans, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tambahTransPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rBtnTransA)
                    .addComponent(rBtnTransB)
                    .addComponent(jLabel16)
                    .addComponent(labelKode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tambahTransPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fieldNoPol, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tambahTransPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(cBoxLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambahRute))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tambahTransPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tambahTransPanelLayout.createSequentialGroup()
                        .addComponent(fieldKapasitas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(btnSubmitTrans, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(tambahTransPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapusRute)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        transTabPane.addTab("Tambah", tambahTransPanel);

        jLabel12.setText("Pilih Angkot:");

        btnHapusBus.setBackground(java.awt.SystemColor.controlDkShadow);
        btnHapusBus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapusBus.setText("Hapus");

        tbBus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbBus);

        tbAngkot.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane8.setViewportView(tbAngkot);

        jLabel20.setText("Pilih Bus:");

        btnHapusAngkot.setBackground(java.awt.SystemColor.controlDkShadow);
        btnHapusAngkot.setForeground(new java.awt.Color(255, 255, 255));
        btnHapusAngkot.setText("Hapus");

        javax.swing.GroupLayout hapusTransPanelLayout = new javax.swing.GroupLayout(hapusTransPanel);
        hapusTransPanel.setLayout(hapusTransPanelLayout);
        hapusTransPanelLayout.setHorizontalGroup(
            hapusTransPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hapusTransPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hapusTransPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(hapusTransPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapusBus, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel20))
                .addGap(0, 23, Short.MAX_VALUE))
            .addGroup(hapusTransPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hapusTransPanelLayout.createSequentialGroup()
                    .addContainerGap(493, Short.MAX_VALUE)
                    .addComponent(btnHapusAngkot, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        hapusTransPanelLayout.setVerticalGroup(
            hapusTransPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hapusTransPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hapusTransPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(hapusTransPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnHapusBus, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(hapusTransPanelLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43))
            .addGroup(hapusTransPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(hapusTransPanelLayout.createSequentialGroup()
                    .addGap(66, 66, 66)
                    .addComponent(btnHapusAngkot, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(192, Short.MAX_VALUE)))
        );

        transTabPane.addTab("Hapus", hapusTransPanel);

        jPanel3.add(transTabPane, "card2");

        fieldUnameAdmin.setText("username");
        fieldUnameAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldUnameAdminActionPerformed(evt);
            }
        });

        jLabel10.setText("Tambah Admin");

        jLabel11.setText("username: ");

        jLabel13.setText("password:");

        fieldPassAdmin.setText("password");

        btnTambahAdmin.setBackground(java.awt.SystemColor.controlDkShadow);
        btnTambahAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnTambahAdmin.setText("Tambah");

        btnHapusAdmin.setBackground(java.awt.SystemColor.controlDkShadow);
        btnHapusAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnHapusAdmin.setText("Hapus");

        jLabel14.setText("Hapus Admin");

        tbAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane10.setViewportView(tbAdmin);

        fieldNamaAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNamaAdminActionPerformed(evt);
            }
        });

        fieldEmailAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldEmailAdminActionPerformed(evt);
            }
        });

        fieldNoHPAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNoHPAdminActionPerformed(evt);
            }
        });

        jLabel21.setText("Nama:");

        jLabel22.setText("Email:");

        jLabel23.setText("No. HP:");

        javax.swing.GroupLayout adminPanelLayout = new javax.swing.GroupLayout(adminPanel);
        adminPanel.setLayout(adminPanelLayout);
        adminPanelLayout.setHorizontalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminPanelLayout.createSequentialGroup()
                        .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(adminPanelLayout.createSequentialGroup()
                                .addComponent(btnTambahAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(89, 89, 89))
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, adminPanelLayout.createSequentialGroup()
                                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(fieldPassAdmin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                        .addComponent(fieldUnameAdmin, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldNamaAdmin)
                                    .addComponent(fieldEmailAdmin)
                                    .addComponent(fieldNoHPAdmin)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23))))
                        .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(adminPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                .addComponent(jLabel14)
                                .addGap(264, 264, 264))
                            .addGroup(adminPanelLayout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnHapusAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        adminPanelLayout.setVerticalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPanelLayout.createSequentialGroup()
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(adminPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel21)
                        .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(adminPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(fieldUnameAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22))
                                .addGap(13, 13, 13)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldPassAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38))
                            .addGroup(adminPanelLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(fieldNamaAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(fieldEmailAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fieldNoHPAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addComponent(btnTambahAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(btnHapusAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        uATabPane.addTab("Admin", adminPanel);

        jLabel15.setText("List user:");

        btnHapusUser.setBackground(java.awt.SystemColor.controlDkShadow);
        btnHapusUser.setForeground(new java.awt.Color(255, 255, 255));
        btnHapusUser.setText("Hapus");

        tbUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane9.setViewportView(tbUser);

        javax.swing.GroupLayout userPanelLayout = new javax.swing.GroupLayout(userPanel);
        userPanel.setLayout(userPanelLayout);
        userPanelLayout.setHorizontalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapusUser, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(324, Short.MAX_VALUE))
        );
        userPanelLayout.setVerticalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnHapusUser, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        uATabPane.addTab("User", userPanel);

        jPanel3.add(uATabPane, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentAdded

    private void fieldNamaTransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNamaTransActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNamaTransActionPerformed

    private void rBtnTransAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnTransAActionPerformed
        jLabel16.setVisible(true);
        labelKode.setVisible(true);
    }//GEN-LAST:event_rBtnTransAActionPerformed

    private void fieldKapasitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldKapasitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldKapasitasActionPerformed

    private void lokasiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lokasiBtnActionPerformed
        // TODO add your handling code here:
        jPanel3.removeAll();
        jPanel3.add(lokTabPane);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_lokasiBtnActionPerformed

    private void transportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transportBtnActionPerformed
        // TODO add your handling code here:
        jPanel3.removeAll();
        jPanel3.add(transTabPane);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_transportBtnActionPerformed

    private void userBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userBtnActionPerformed
        jPanel3.removeAll();
        jPanel3.add(uATabPane);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_userBtnActionPerformed

    private void fieldUnameAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldUnameAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldUnameAdminActionPerformed

    private void wisRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wisRBtnActionPerformed
        tarifLok.setVisible(true);
        jLabel24.setVisible(true);
    }//GEN-LAST:event_wisRBtnActionPerformed

    private void nonWisRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nonWisRBtnActionPerformed
        tarifLok.setVisible(false);
        jLabel24.setVisible(false);
    }//GEN-LAST:event_nonWisRBtnActionPerformed

    private void tarifLokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarifLokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tarifLokActionPerformed

    private void fieldNamaAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNamaAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNamaAdminActionPerformed

    private void fieldEmailAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldEmailAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldEmailAdminActionPerformed

    private void fieldNoHPAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNoHPAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNoHPAdminActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void rBtnTransBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnTransBActionPerformed
        jLabel16.setVisible(false);
        labelKode.setVisible(false);
    }//GEN-LAST:event_rBtnTransBActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adminPanel;
    private javax.swing.JButton btnHapusAdmin;
    private javax.swing.JButton btnHapusAngkot;
    private javax.swing.JButton btnHapusBus;
    private javax.swing.JButton btnHapusNonWisata;
    private javax.swing.JButton btnHapusRute;
    private javax.swing.JButton btnHapusUser;
    private javax.swing.JButton btnHapusWisata;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnSubmitTrans;
    private javax.swing.JButton btnTambahAdmin;
    private javax.swing.JButton btnTambahRute;
    private javax.swing.ButtonGroup butGroupJenis;
    private javax.swing.JComboBox<String> cBoxLokasi;
    private javax.swing.JTextPane descPane;
    private javax.swing.JTextField fieldEmailAdmin;
    private javax.swing.JTextField fieldKapasitas;
    private javax.swing.JTextField fieldNamaAdmin;
    private javax.swing.JTextField fieldNamaTrans;
    private javax.swing.JTextField fieldNoHPAdmin;
    private javax.swing.JTextField fieldNoPol;
    private javax.swing.JPasswordField fieldPassAdmin;
    private javax.swing.JTextField fieldTarifTrans;
    private javax.swing.JTextField fieldUnameAdmin;
    private javax.swing.JPanel hapusLokPanel;
    private javax.swing.JPanel hapusTransPanel;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel labelKode;
    private javax.swing.JTabbedPane lokTabPane;
    private javax.swing.JButton lokasiBtn;
    private javax.swing.JTextField namaTempatField;
    private javax.swing.JRadioButton nonWisRBtn;
    private javax.swing.JComboBox<String> pilihLokBox;
    private javax.swing.JRadioButton rBtnTransA;
    private javax.swing.JRadioButton rBtnTransB;
    private javax.swing.JPanel tambahLokPanel;
    private javax.swing.JPanel tambahTransPanel;
    private javax.swing.JTextField tarifLok;
    private javax.swing.JTable tbAdmin;
    private javax.swing.JTable tbAngkot;
    private javax.swing.JTable tbBus;
    private javax.swing.JTable tbNonWisata;
    private javax.swing.JTable tbRute;
    private javax.swing.JTable tbUser;
    private javax.swing.JTable tbWisata;
    private javax.swing.JTabbedPane transTabPane;
    private javax.swing.JButton transportBtn;
    private javax.swing.JTabbedPane uATabPane;
    private javax.swing.JButton userBtn;
    private javax.swing.JPanel userPanel;
    private javax.swing.JRadioButton wisRBtn;
    // End of variables declaration//GEN-END:variables
    
    public void resetLokasi(){
        namaTempatField.setText("");
        idField.setText("");
        descPane.setText("");
        tarifLok.setText("");
    }
    
    public void showMessage(String message, String title, int type){
        JOptionPane.showMessageDialog(null, message, title, type);
    }
    
    public String getNamaTempatField() {
        return namaTempatField.getText();
    }
    
    public String getDescPane() {
        return descPane.getText();
    }

    public void setDescPane(JTextPane descPane) {
        this.descPane = descPane;
    }

    public String getIdField() {
        return idField.getText();
    }

    public void setIdField(JTextField idField) {
        this.idField = idField;
    }

    public JRadioButton getNonWisRBtn() {
        return nonWisRBtn;
    }

    public void setNonWisRBtn(JRadioButton nonWisRBtn) {
        this.nonWisRBtn = nonWisRBtn;
    }

    public String getPilihLokBox() {
        return pilihLokBox.getItemAt(pilihLokBox.getSelectedIndex());
    }

    public void setPilihLokBox(JComboBox<String> pilihLokBox) {
        this.pilihLokBox = pilihLokBox;
    }

    public JButton getBtnSubmit() {
        return btnSubmit;
    }

    public void setSubmitBtn(JButton submitBtn) {
        this.btnSubmit = submitBtn;
    }

    public JRadioButton getWisRBtn() {
        return wisRBtn;
    }

    public void setWisRBtn(JRadioButton wisRBtn) {
        this.wisRBtn = wisRBtn;
    }
    
    public String getLokasi(){
        if(wisRBtn.isSelected()){
            return "wisata";
        } else {
            return "nonWisata";
        }
    }

    public JTextField getIdField1() {
        return fieldNoPol;
    }

    public void setIdField1(JTextField idField1) {
        this.fieldNoPol = idField1;
    }

    public JButton getHapusLokBtn() {
        return btnHapusNonWisata;
    }

    public void setHapusLokBtn(JButton hapusLokBtn) {
        this.btnHapusNonWisata = hapusLokBtn;
    }

    public String getTarifLok() {
        return tarifLok.getText();
    }

    public void setTarifLok(JTextField tarifLok) {
        this.tarifLok = tarifLok;
    }

    public JTable getTbWisata() {
        return tbWisata;
    }
    
    public void setTbWisata(DefaultTableModel x) {
        this.tbWisata.setModel(x);
    }
    
    public int getSelectedWisata(){
        return tbWisata.getSelectedRow();
    }

    public JTable getTbNonWisata() {
        return tbNonWisata;
    }
    
    public void setTbNonWisata(DefaultTableModel x) {
        this.tbNonWisata.setModel(x);
    }
    
    public int getSelectedNonWisata(){
        return tbNonWisata.getSelectedRow();
    }

    public JButton getBtnSubmitTrans() {
        return btnSubmitTrans;
    }

    public void setBtnSubmitTrans(JButton btnSubmitTrans) {
        this.btnSubmitTrans = btnSubmitTrans;
    }

    public int getFieldKapasitas() {
        return Integer.parseInt(fieldKapasitas.getText());
    }

    public void setFieldKapasitas(JTextField fieldKapasitas) {
        this.fieldKapasitas = fieldKapasitas;
    }

    public String getFieldNamaTrans() {
        return fieldNamaTrans.getText();
    }

    public void setFieldNamaTrans(JTextField fieldNamaTrans) {
        this.fieldNamaTrans = fieldNamaTrans;
    }

    public String getFieldNoPol() {
        return fieldNoPol.getText();
    }

    public void setFieldNoPol(JTextField fieldNoPol) {
        this.fieldNoPol = fieldNoPol;
    }

    public int getFieldTarifTrans() {
        return Integer.parseInt(fieldTarifTrans.getText());
    }

    public void setFieldTarifTrans(JTextField fieldTarifTrans) {
        this.fieldTarifTrans = fieldTarifTrans;
    }

    public JRadioButton getrBtnTransA() {
        return rBtnTransA;
    }

    public void setrBtnTransA(JRadioButton rBtnTransA) {
        this.rBtnTransA = rBtnTransA;
    }

    public JRadioButton getrBtnTransB() {
        return rBtnTransB;
    }

    public void setrBtnTransB(JRadioButton rBtnTransB) {
        this.rBtnTransB = rBtnTransB;
    }
    
    public String getJenisTrans(){
        if (rBtnTransA.isSelected()){
            return "angkot";
        } else {
            return "bus";
        }
    }
    
    
    public JButton getHapusAdminBtn() {
        return btnHapusAdmin;
    }

    public void setHapusAdminBtn(JButton hapusAdminBtn) {
        this.btnHapusAdmin = hapusAdminBtn;
    }
    

    public JTable getTbAngkot() {
        return tbAngkot;
    }

    public void setTbAngkot(DefaultTableModel x) {
        this.tbAngkot.setModel(x);
    }
    
    public int getSelectedAngkot() {
        return tbAngkot.getSelectedRow();
    }

    public JTable getTbBus() {
        return tbBus;
    }

    public void setTbBus(DefaultTableModel x) {
        this.tbBus.setModel(x);
    }
    
    public int getSelectedBus(){
        return tbBus.getSelectedRow();
    }

    public String getFieldPassAdmin() {
        return fieldPassAdmin.getText();
    }

    public void setFieldPassAdmin(JPasswordField fieldPassAdmin) {
        this.fieldPassAdmin = fieldPassAdmin;
    }

    public String getFieldUnameAdmin() {
        return fieldUnameAdmin.getText();
    }

    public void setFieldUnameAdmin(JTextField fieldUnameAdmin) {
        this.fieldUnameAdmin = fieldUnameAdmin;
    }

    public JButton getTambahAdminBtn() {
        return btnTambahAdmin;
    }

    public void setTambahAdminBtn(JButton tambahAdminBtn) {
        this.btnTambahAdmin = tambahAdminBtn;
    }

    public String getFieldEmailAdmin() {
        return fieldEmailAdmin.getText();
    }

    public void setFieldEmailAdmin(JTextField fieldEmailAdmin) {
        this.fieldEmailAdmin = fieldEmailAdmin;
    }

    public String getFieldNamaAdmin() {
        return fieldNamaAdmin.getText();
    }

    public void setFieldNamaAdmin(JTextField fieldNamaAdmin) {
        this.fieldNamaAdmin = fieldNamaAdmin;
    }

    public String getFieldNoHPAdmin() {
        return fieldNoHPAdmin.getText();
    }

    public void setFieldNoHPAdmin(JTextField fieldNoHPAdmin) {
        this.fieldNoHPAdmin = fieldNoHPAdmin;
    }

    public JTable getTbAdmin() {
        return tbAdmin;
    }

    public void setTbAdmin(DefaultTableModel x) {
        this.tbAdmin.setModel(x);
    }
    
    public int getSelectedAdmin(){
        return tbAdmin.getSelectedRow();
    }

    public JTable getTbUser() {
        return tbUser;
    }

    public void setTbUser(DefaultTableModel x) {
        this.tbUser.setModel(x);
    }
    
    public int getSelectedUser(){
        return tbUser.getSelectedRow();
    }

    public JButton getBtnHapusAdmin() {
        return btnHapusAdmin;
    }

    public void setBtnHapusAdmin(JButton btnHapusAdmin) {
        this.btnHapusAdmin = btnHapusAdmin;
    }

    public JButton getBtnHapusAngkot() {
        return btnHapusAngkot;
    }

    public void setBtnHapusAngkot(JButton btnHapusAngkot) {
        this.btnHapusAngkot = btnHapusAngkot;
    }

    public JButton getBtnHapusBus() {
        return btnHapusBus;
    }

    public void setBtnHapusBus(JButton btnHapusBus) {
        this.btnHapusBus = btnHapusBus;
    }

    public JButton getBtnHapusNonWisata() {
        return btnHapusNonWisata;
    }

    public void setBtnHapusNonWisata(JButton btnHapusNonWisata) {
        this.btnHapusNonWisata = btnHapusNonWisata;
    }

    public JButton getBtnHapusUser() {
        return btnHapusUser;
    }

    public void setBtnHapusUser(JButton btnHapusUser) {
        this.btnHapusUser = btnHapusUser;
    }

    public JButton getBtnHapusWisata() {
        return btnHapusWisata;
    }

    public void setBtnHapusWisata(JButton btnHapusWisata) {
        this.btnHapusWisata = btnHapusWisata;
    }

    public JButton getBtnLogOut() {
        return btnLogOut;
    }

    public void setBtnLogOut(JButton btnLogOut) {
        this.btnLogOut = btnLogOut;
    }

    public JLabel getLabelKode() {
        return labelKode;
    }

    public void setLabelKode(String kode) {
        labelKode.setText(kode);
    }

    public JButton getBtnHapusRute() {
        return btnHapusRute;
    }

    public void setBtnHapusRute(JButton btnHapusRute) {
        this.btnHapusRute = btnHapusRute;
    }

    public JButton getBtnTambahRute() {
        return btnTambahRute;
    }

    public void setBtnTambahRute(JButton btnTambahRute) {
        this.btnTambahRute = btnTambahRute;
    }

    public JTable getTbRute() {
        return tbRute;
    }
    
    public int getSelectedRute(){
        return tbRute.getSelectedRow();
    }
    
    public String getIsiTbRute(int i){
        return tbRute.getModel().getValueAt(i, 0).toString();
    }
    
    public int getRowTbRute(){
        return tbRute.getRowCount();
    }

    public void setTbRute(DefaultTableModel x) {
        tbRute.setModel(x);
    }
    
    public void hapusRowTbRute(int i){
        ((DefaultTableModel)tbRute.getModel()).removeRow(i);
    }
    
    public void resetTbRute(){
        tbRute.removeAll();
    }

    public String getcBoxLokasi() {
        return cBoxLokasi.getItemAt(cBoxLokasi.getSelectedIndex());
    }

    public void setcBoxLokasi(JComboBox<String> cBoxLokasi) {
        this.cBoxLokasi = cBoxLokasi;
    }
    
    
    
    public void addActionListener(ActionListener x){
        btnSubmit.addActionListener(x);
        btnSubmitTrans.addActionListener(x);
        btnTambahAdmin.addActionListener(x);
        btnHapusNonWisata.addActionListener(x);
        btnHapusWisata.addActionListener(x);
        btnHapusAdmin.addActionListener(x);
        btnHapusUser.addActionListener(x);
        btnHapusAngkot.addActionListener(x);
        btnHapusBus.addActionListener(x);
        btnLogOut.addActionListener(x);
        btnTambahRute.addActionListener(x);
        btnHapusRute.addActionListener(x);
    }   
    
    public void addMouseAdapter(MouseAdapter x){
        tbWisata.addMouseListener(x);
        tbNonWisata.addMouseListener(x);
        tbAdmin.addMouseListener(x);
        tbUser.addMouseListener(x);
        tbAngkot.addMouseListener(x);
        tbBus.addMouseListener(x);
        tbRute.addMouseListener(x);
    }
    
    
    
}

