/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Tri Jaka
 */
public class AdminFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminFrame
     */
    public AdminFrame() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butGroupJenis = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        lokasiBtn = new javax.swing.JButton();
        transportBtn = new javax.swing.JButton();
        userBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lokTabPane = new javax.swing.JTabbedPane();
        tambahLokPanel = new javax.swing.JPanel();
        namaTempatField = new javax.swing.JTextField();
        wisRBtn = new javax.swing.JRadioButton();
        nonWisRBtn = new javax.swing.JRadioButton();
        idField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        descPane = new javax.swing.JTextPane();
        submitBtn = new javax.swing.JButton();
        pilihLokBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        hapusLokPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        transTabPane = new javax.swing.JTabbedPane();
        tambahLokPanel1 = new javax.swing.JPanel();
        namaTransField1 = new javax.swing.JTextField();
        wisRBtn1 = new javax.swing.JRadioButton();
        nonWisRBtn1 = new javax.swing.JRadioButton();
        idField1 = new javax.swing.JTextField();
        submitBtn1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Kapasitas = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        hapusLokPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        uATabPane = new javax.swing.JTabbedPane();
        tambahLokPanel2 = new javax.swing.JPanel();
        namaField2 = new javax.swing.JTextField();
        wisRBtn2 = new javax.swing.JRadioButton();
        nonWisRBtn2 = new javax.swing.JRadioButton();
        idField2 = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        descPane2 = new javax.swing.JTextPane();
        submitBtn2 = new javax.swing.JButton();
        pilihLokBox2 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        hapusLokPanel2 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        jLabel18 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 500));
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setPreferredSize(new java.awt.Dimension(335, 200));

        lokasiBtn.setBackground(new java.awt.Color(102, 102, 102));
        lokasiBtn.setText("lokasiBtn");

        transportBtn.setBackground(new java.awt.Color(102, 102, 102));
        transportBtn.setText("transportBtn");

        userBtn.setBackground(new java.awt.Color(102, 102, 102));
        userBtn.setText("Admin & User");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lokasiBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(transportBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(userBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lokasiBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setLayout(new java.awt.CardLayout());

        namaTempatField.setText("Nama Tempat");
        namaTempatField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaTempatFieldActionPerformed(evt);
            }
        });

        butGroupJenis.add(wisRBtn);
        wisRBtn.setText("Wisata");

        butGroupJenis.add(nonWisRBtn);
        nonWisRBtn.setText("Non-Wisata");

        idField.setText("ID Baru");

        jScrollPane2.setViewportView(descPane);

        submitBtn.setText("Submit");

        pilihLokBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Nama Tempat: ");

        jLabel2.setText("Jenis: ");

        jLabel3.setText("ID Baru:");

        jLabel4.setText("Lokasi: ");

        jLabel6.setText("Deskripsi Tempat:");

        javax.swing.GroupLayout tambahLokPanelLayout = new javax.swing.GroupLayout(tambahLokPanel);
        tambahLokPanel.setLayout(tambahLokPanelLayout);
        tambahLokPanelLayout.setHorizontalGroup(
            tambahLokPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahLokPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tambahLokPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tambahLokPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(submitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(idField)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tambahLokPanelLayout.createSequentialGroup()
                            .addComponent(wisRBtn)
                            .addGap(18, 18, 18)
                            .addComponent(nonWisRBtn))
                        .addComponent(namaTempatField, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                        .addComponent(pilihLokBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(tambahLokPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tambahLokPanelLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 132, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        tambahLokPanelLayout.setVerticalGroup(
            tambahLokPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahLokPanelLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(tambahLokPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tambahLokPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tambahLokPanelLayout.createSequentialGroup()
                        .addComponent(namaTempatField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tambahLokPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(wisRBtn)
                            .addComponent(nonWisRBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pilihLokBox, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(submitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addContainerGap())
        );

        pilihLokBox.getAccessibleContext().setAccessibleDescription("");

        lokTabPane.addTab("Tambah", tambahLokPanel);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel5.setText("Pilih Lokasi:");

        jButton1.setText("Hapus");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout hapusLokPanelLayout = new javax.swing.GroupLayout(hapusLokPanel);
        hapusLokPanel.setLayout(hapusLokPanelLayout);
        hapusLokPanelLayout.setHorizontalGroup(
            hapusLokPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(hapusLokPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(hapusLokPanelLayout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 321, Short.MAX_VALUE))
        );
        hapusLokPanelLayout.setVerticalGroup(
            hapusLokPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hapusLokPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap())
        );

        lokTabPane.addTab("Hapus", hapusLokPanel);

        jPanel3.add(lokTabPane, "card2");

        namaTransField1.setText("Nama Transportasi");
        namaTransField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaTransField1ActionPerformed(evt);
            }
        });

        butGroupJenis.add(wisRBtn1);
        wisRBtn1.setText("Angkot");
        wisRBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wisRBtn1ActionPerformed(evt);
            }
        });

        butGroupJenis.add(nonWisRBtn1);
        nonWisRBtn1.setText("Bus");

        idField1.setText("ID Baru");

        submitBtn1.setText("Submit");

        jLabel7.setText("Nama Transportasi:");

        jLabel8.setText("Jenis: ");

        jLabel9.setText("ID Baru:");

        Kapasitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KapasitasActionPerformed(evt);
            }
        });

        jLabel19.setText("Kapasitas:");

        javax.swing.GroupLayout tambahLokPanel1Layout = new javax.swing.GroupLayout(tambahLokPanel1);
        tambahLokPanel1.setLayout(tambahLokPanel1Layout);
        tambahLokPanel1Layout.setHorizontalGroup(
            tambahLokPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahLokPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tambahLokPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tambahLokPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(submitBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(idField1)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tambahLokPanel1Layout.createSequentialGroup()
                            .addComponent(wisRBtn1)
                            .addGap(18, 18, 18)
                            .addComponent(nonWisRBtn1))
                        .addComponent(namaTransField1, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(jLabel19)
                    .addComponent(Kapasitas, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(245, Short.MAX_VALUE))
        );
        tambahLokPanel1Layout.setVerticalGroup(
            tambahLokPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahLokPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaTransField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tambahLokPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wisRBtn1)
                    .addComponent(nonWisRBtn1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Kapasitas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(submitBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addContainerGap())
        );

        transTabPane.addTab("Tambah", tambahLokPanel1);

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jList2);

        jLabel12.setText("Pilih Lokasi:");

        jButton2.setText("Hapus");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout hapusLokPanel1Layout = new javax.swing.GroupLayout(hapusLokPanel1);
        hapusLokPanel1.setLayout(hapusLokPanel1Layout);
        hapusLokPanel1Layout.setHorizontalGroup(
            hapusLokPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4)
            .addGroup(hapusLokPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(hapusLokPanel1Layout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 321, Short.MAX_VALUE))
        );
        hapusLokPanel1Layout.setVerticalGroup(
            hapusLokPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hapusLokPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(9, 9, 9)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap())
        );

        transTabPane.addTab("Hapus", hapusLokPanel1);

        jPanel3.add(transTabPane, "card2");

        namaField2.setText("Nama Tempat");
        namaField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaField2ActionPerformed(evt);
            }
        });

        butGroupJenis.add(wisRBtn2);
        wisRBtn2.setText("Wisata");

        butGroupJenis.add(nonWisRBtn2);
        nonWisRBtn2.setText("Non-Wisata");

        idField2.setText("ID Baru");

        jScrollPane5.setViewportView(descPane2);

        submitBtn2.setText("Submit");

        pilihLokBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel13.setText("Nama Tempat: ");

        jLabel14.setText("Jenis: ");

        jLabel15.setText("ID Baru:");

        jLabel16.setText("Lokasi: ");

        jLabel17.setText("Deskripsi Tempat:");

        javax.swing.GroupLayout tambahLokPanel2Layout = new javax.swing.GroupLayout(tambahLokPanel2);
        tambahLokPanel2.setLayout(tambahLokPanel2Layout);
        tambahLokPanel2Layout.setHorizontalGroup(
            tambahLokPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahLokPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tambahLokPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tambahLokPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(submitBtn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(idField2)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tambahLokPanel2Layout.createSequentialGroup()
                            .addComponent(wisRBtn2)
                            .addGap(18, 18, 18)
                            .addComponent(nonWisRBtn2))
                        .addComponent(namaField2, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                        .addComponent(pilihLokBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(tambahLokPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tambahLokPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(0, 132, Short.MAX_VALUE))
                    .addComponent(jScrollPane5))
                .addContainerGap())
        );
        tambahLokPanel2Layout.setVerticalGroup(
            tambahLokPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahLokPanel2Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(tambahLokPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tambahLokPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tambahLokPanel2Layout.createSequentialGroup()
                        .addComponent(namaField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tambahLokPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(wisRBtn2)
                            .addComponent(nonWisRBtn2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idField2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pilihLokBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(submitBtn2, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addContainerGap())
        );

        uATabPane.addTab("Tambah", tambahLokPanel2);

        jList3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane6.setViewportView(jList3);

        jLabel18.setText("Pilih Lokasi:");

        jButton3.setText("Hapus");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout hapusLokPanel2Layout = new javax.swing.GroupLayout(hapusLokPanel2);
        hapusLokPanel2.setLayout(hapusLokPanel2Layout);
        hapusLokPanel2Layout.setHorizontalGroup(
            hapusLokPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6)
            .addGroup(hapusLokPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(hapusLokPanel2Layout.createSequentialGroup()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 321, Short.MAX_VALUE))
        );
        hapusLokPanel2Layout.setVerticalGroup(
            hapusLokPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hapusLokPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addGap(9, 9, 9)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap())
        );

        uATabPane.addTab("Hapus", hapusLokPanel2);

        jPanel3.add(uATabPane, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentAdded

    private void namaTempatFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaTempatFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaTempatFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void namaTransField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaTransField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaTransField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void namaField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaField2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void wisRBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wisRBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wisRBtn1ActionPerformed

    private void KapasitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KapasitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KapasitasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFrame().setVisible(true);
                jPanel3.removeAll();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Kapasitas;
    private javax.swing.ButtonGroup butGroupJenis;
    private javax.swing.JTextPane descPane;
    private javax.swing.JTextPane descPane2;
    private javax.swing.JPanel hapusLokPanel;
    private javax.swing.JPanel hapusLokPanel1;
    private javax.swing.JPanel hapusLokPanel2;
    private javax.swing.JTextField idField;
    private javax.swing.JTextField idField1;
    private javax.swing.JTextField idField2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane lokTabPane;
    private javax.swing.JButton lokasiBtn;
    private javax.swing.JTextField namaField2;
    private javax.swing.JTextField namaTempatField;
    private javax.swing.JTextField namaTransField1;
    private javax.swing.JRadioButton nonWisRBtn;
    private javax.swing.JRadioButton nonWisRBtn1;
    private javax.swing.JRadioButton nonWisRBtn2;
    private javax.swing.JComboBox<String> pilihLokBox;
    private javax.swing.JComboBox<String> pilihLokBox2;
    private javax.swing.JButton submitBtn;
    private javax.swing.JButton submitBtn1;
    private javax.swing.JButton submitBtn2;
    private javax.swing.JPanel tambahLokPanel;
    private javax.swing.JPanel tambahLokPanel1;
    private javax.swing.JPanel tambahLokPanel2;
    private javax.swing.JTabbedPane transTabPane;
    private javax.swing.JButton transportBtn;
    private javax.swing.JTabbedPane uATabPane;
    private javax.swing.JButton userBtn;
    private javax.swing.JRadioButton wisRBtn;
    private javax.swing.JRadioButton wisRBtn1;
    private javax.swing.JRadioButton wisRBtn2;
    // End of variables declaration//GEN-END:variables
}
