/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.NonWisata;
import Model.Wisata;
import javax.swing.JTextArea;

/**
 *
 * @author Tri Jaka
 */
public class InfoLokasi extends javax.swing.JFrame {

    Wisata wis;
    NonWisata nowis;
    String jenis;
    public InfoLokasi(String jenis, Wisata wis, NonWisata nowis) {
        initComponents();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        System.out.println(jenis);
        if (jenis =="Wisata"){
            this.wis = wis;
            setjTextArea1("Nama Tempat      : "+wis.getNama()+'\n'+
                          "Jenis Tempat     : "+jenis+'\n'+
                          "Lokasi Tempat    : "+wis.getAlamat()+'\n'+
                          "Tarif Tempat     : "+wis.getHarga()+'\n'+
                          "Deskripsi Tempat : "+wis.getDeskripsi());
        } else if (jenis == "NonWisata") {
            this.nowis = nowis;
            setjTextArea1("Nama Tempat      : "+nowis.getNama()+'\n'+
                          "Jenis Tempat     : "+jenis+'\n'+
                          "Lokasi Tempat    : "+nowis.getAlamat()+'\n'+
                          "Deskripsi Tempat : "+nowis.getDeskripsi());
        }
        this.jenis = jenis;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    public JTextArea getjTextArea1() {
        return jTextArea1;
    }

    public void setjTextArea1(String info) {
        this.jTextArea1.setText(info);
    }

    
    
}
